### ISSUE TITLE
licences 

### ISSUE THREAD

**Issue by hnadyfff** [zhaoyun0071/Disco-Diffusion-Local#6]
this program is free or i should buy licences ?
if i should how i can reach you if i don't have wechat  ?

**Comment by zhaoyun0071** [comment]
> this program is free or i should buy licences ?
> if i should how i can reach you if i don't have wechat  ?

【淘宝】https://m.tb.cn/h.fCwXy1H?tk=VgLA2q9qUzs「DISCO DIFFUSION AI作画离线版，让自己的电脑也能画画」
点击链接直接打开
